### ISSUE TITLE
trouble setting custom palette

### ISSUE THREAD

**Issue by allaway** [howardjp/waterfall#3]
Hi there, 

Perhaps I am simply doing something wrong, but mainPalette doesn't behave as I would expect. For example, if I try to color a plot with 7 mutations types present using the following code: 

`cols <- c("blue", "red", "pink", "green", "orange", "black", "brown")`

`waterfall(soms, fileType = "MAF", mainRecurCutoff = 0.3, mainDropMut = TRUE, mainPalette = cols)`

I end up with a plot that has variants colored with a blue-red-green gradient, rather than the 7 explicit colors that I included in cols. Why is this? 

Thanks for the great package though - very nice for visualizing mafs!

**Comment by howardjp** [comment]
@allaway, I'm sorry to say you have a different waterfall.  The repo you're looking for is [GenVisR](https://github.com/griffithlab/GenVisR).  Apparently there is a way to transfer issues between repos, so I will leave this open.

**Comment by allaway** [comment]
Oh boy, that's embarrassing. Thanks for the help!

Cheers,
Robert
